baseURL = "https://cyril.coffee/"
languageCode = "en-us"
title = "Cyril, A Website"
theme = "minimal"

[params]
    author = "Cyril Van Dyke"
    description = "Software Engineer, Corgi Aficionado, Seltzer Sommelier"
    githubUsername = "cyril-vandyke"
    accent = "purple"
    showBorder = true
    backgroundColor = "lavender"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/page/about/"
    name = "About Me"
    weight = 3

[[menu.icon]]
    url = "mailto:cyril.vandyke+coffee@gmail.com"
    name = "envelope-o"
    weight = 4

[[menu.icon]]
    url = "https://github.com/cyril-vandyke/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/cyril_irl/"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/cyril-van-dyke-35880160/"
    name = "linkedin"
    weight = 3